"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.templateClient = exports.signTaskClient = exports.serviceClient = exports.userClient = exports.sealClient = exports.orgClient = exports.euiClient = exports.docClient = exports.corpClient = void 0;
var corp_1 = require("./corp");
Object.defineProperty(exports, "corpClient", { enumerable: true, get: function () { return corp_1.corpClient; } });
var doc_1 = require("./doc");
Object.defineProperty(exports, "docClient", { enumerable: true, get: function () { return doc_1.docClient; } });
var eui_1 = require("./eui");
Object.defineProperty(exports, "euiClient", { enumerable: true, get: function () { return eui_1.euiClient; } });
var org_1 = require("./org");
Object.defineProperty(exports, "orgClient", { enumerable: true, get: function () { return org_1.orgClient; } });
var seal_1 = require("./seal");
Object.defineProperty(exports, "sealClient", { enumerable: true, get: function () { return seal_1.sealClient; } });
var user_1 = require("./user");
Object.defineProperty(exports, "userClient", { enumerable: true, get: function () { return user_1.userClient; } });
var service_1 = require("./service");
Object.defineProperty(exports, "serviceClient", { enumerable: true, get: function () { return service_1.serviceClient; } });
var sign_task_1 = require("./sign_task");
Object.defineProperty(exports, "signTaskClient", { enumerable: true, get: function () { return sign_task_1.signTaskClient; } });
var template_1 = require("./template");
Object.defineProperty(exports, "templateClient", { enumerable: true, get: function () { return template_1.templateClient; } });
