import { AbstractClient } from "../../common/abstract_client";
import { ClientConfig } from "../../common/interface";
import { CreateRequest, CreateResponse, CreateWithTemplateRequest, CreateWithTemplateResponse, AddDocRequest, AddDocResponse, DeleteDocRequest, DeleteDocResponse, AddFieldRequest, AddFieldResponse, DeleteFieldRequest, DeleteFieldResponse, FillFieldValuesRequest, FillFieldValuesResponse, AddAttachRequest, AddAttachResponse, DeleteAttachRequest, DeleteAttachResponse, AddActorRequest, AddActorResponse, DeleteActorRequest, DeleteActorResponse, StartRequest, StartResponse, CancelRequest, CancelResponse, FinalizeDocRequest, FinalizeDocResponse, UrgeSignTaskRequest, UrgeSignTaskResponse, BlockRequest, BlockResponse, UnblockRequest, UnblockResponse, FinishRequest, FinishResponse, GetOwnerListRequest, GetOwnerListResponse, GetDetailRequest, GetDetailResponse, GetOwnerDownLoadUrlRequest, GetOwnerDownLoadUrlResponse, GetSignTaskEditUrlRequest, GetSignTaskEditUrlResponse, GetSignTaskPreviewUrlRequest, GetSignTaskPreviewUrlResponse, GetActorUrlRequest, GetActorUrlResponse, GetActorBatchSignTaskUrlRequest, GetActorBatchSignTaskUrlResponse, GetSignTaskActorListRequest, GetSignTaskActorListResponse, GetSignTaskFieldListRequest, GetSignTaskFieldListResponse, GetSignTaskApprovalInfoRequest, GetSignTaskApprovalInfoResponse, GetSignTaskCatalogListRequest, GetSignTaskCatalogListResponse, GetSignTaskBusinessTypeListRequest, GetSignTaskBusinessTypeListResponse, GetEvidenceReportDownloadRequest, GetEvidenceReportDownloadResponse, GetActorFacePictureRequest, GetActorFacePictureResponse, GetSignTaskPicDownLoadUrlRequest, GetSignTaskPicDownLoadUrlResponse, AbolishRequest, AbolishResponse, DeleteRequest, DeleteResponse, GetV3ActorSignTaskUrlRequest, GetV3ActorSignTaskUrlResponse } from "./sign_task_models";
export declare class Client extends AbstractClient {
    constructor(clientConfig: ClientConfig);
    /** 创建签署任务(基于文档) */
    create(req: CreateRequest): Promise<CreateResponse>;
    /** 创建签署任务(基于签署任务模板) */
    createWithTemplate(req: CreateWithTemplateRequest): Promise<CreateWithTemplateResponse>;
    /** 添加签署任务文档 */
    addDoc(req: AddDocRequest): Promise<AddDocResponse>;
    /** 移除签署任务文档 */
    deleteDoc(req: DeleteDocRequest): Promise<DeleteDocResponse>;
    /** 添加签署任务控件 */
    addField(req: AddFieldRequest): Promise<AddFieldResponse>;
    /** 移除签署任务控件 */
    deleteField(req: DeleteFieldRequest): Promise<DeleteFieldResponse>;
    /** 填写签署任务控件内容 */
    fillFieldValues(req: FillFieldValuesRequest): Promise<FillFieldValuesResponse>;
    /** 添加签署任务附件 */
    addAttach(req: AddAttachRequest): Promise<AddAttachResponse>;
    /** 移除签署任务附件 */
    deleteAttach(req: DeleteAttachRequest): Promise<DeleteAttachResponse>;
    /** 添加签署任务参与方 */
    addActor(req: AddActorRequest): Promise<AddActorResponse>;
    /** 移除签署任务参与方 */
    deleteActor(req: DeleteActorRequest): Promise<DeleteActorResponse>;
    /** 获取签署任务编辑链接 */
    getSignTaskEditUrl(req: GetSignTaskEditUrlRequest): Promise<GetSignTaskEditUrlResponse>;
    /** 获取签署任务预览链接 */
    getSignTaskPreviewUrl(req: GetSignTaskPreviewUrlRequest): Promise<GetSignTaskPreviewUrlResponse>;
    /** 获取参与方签署链接 */
    getActorUrl(req: GetActorUrlRequest): Promise<GetActorUrlResponse>;
    /** 获取参与方批量签署链接 */
    getActorBatchSignTaskUrl(req: GetActorBatchSignTaskUrlRequest): Promise<GetActorBatchSignTaskUrlResponse>;
    /** 获取参与方签署链接（API3.0任务专属） */
    getV3ActorSignTaskUrl(req: GetV3ActorSignTaskUrlRequest): Promise<GetV3ActorSignTaskUrlResponse>;
    /** 提交签署任务 */
    start(req: StartRequest): Promise<StartResponse>;
    /** 撤销签署任务 */
    cancel(req: CancelRequest): Promise<CancelResponse>;
    /** 定稿签署任务 */
    finalizeDoc(req: FinalizeDocRequest): Promise<FinalizeDocResponse>;
    /** 催办签署任务 */
    urgeSignTask(req: UrgeSignTaskRequest): Promise<UrgeSignTaskResponse>;
    /** 阻塞签署任务 */
    block(req: BlockRequest): Promise<BlockResponse>;
    /** 解阻签署任务 */
    unblock(req: UnblockRequest): Promise<UnblockResponse>;
    /** 结束签署任务 */
    finish(req: FinishRequest): Promise<FinishResponse>;
    /** 作废签署任务 */
    abolish(req: AbolishRequest): Promise<AbolishResponse>;
    /** 删除签署任务 */
    delete(req: DeleteRequest): Promise<DeleteResponse>;
    /** 查询签署任务详情 */
    getDetail(req: GetDetailRequest): Promise<GetDetailResponse>;
    /** 查询签署任务列表 */
    getOwnerList(req: GetOwnerListRequest): Promise<GetOwnerListResponse>;
    /** 查询参与方身份信息 */
    getSignTaskActorList(req: GetSignTaskActorListRequest): Promise<GetSignTaskActorListResponse>;
    /** 查询参与方填写内容 */
    getSignTaskFieldList(req: GetSignTaskFieldListRequest): Promise<GetSignTaskFieldListResponse>;
    /** 查询签署任务审批信息 */
    getSignTaskApprovalInfo(req: GetSignTaskApprovalInfoRequest): Promise<GetSignTaskApprovalInfoResponse>;
    /** 查询企业签署任务文件夹列表 */
    getSignTaskCatalogList(req: GetSignTaskCatalogListRequest): Promise<GetSignTaskCatalogListResponse>;
    /** 查询签署业务类型列表 */
    getSignTaskBusinessTypeList(req: GetSignTaskBusinessTypeListRequest): Promise<GetSignTaskBusinessTypeListResponse>;
    /** 获取签署过程保全报告下载地址 */
    getEvidenceReportDownloadUrl(req: GetEvidenceReportDownloadRequest): Promise<GetEvidenceReportDownloadResponse>;
    /** 获取签署文档下载地址 */
    getOwnerDownLoadUrl(req: GetOwnerDownLoadUrlRequest): Promise<GetOwnerDownLoadUrlResponse>;
    /** 获取签署任务参与方刷脸底图 */
    getActorFacePicture(req: GetActorFacePictureRequest): Promise<GetActorFacePictureResponse>;
    /** 获取图片版签署文档下载地址 */
    getSignTaskPicDownLoadUrl(req: GetSignTaskPicDownLoadUrlRequest): Promise<GetSignTaskPicDownLoadUrlResponse>;
}
